# Book settings
title: Underworld 3
author: Louis Moresi 
logo: Figures/AuWorldEQ.jpg
exclude_patterns: ["README.md", "Notes/*", "Scripts/*", "Lectures/*.reveal.md", "*/WIP/*", "*/output/*", "*/Developers/*"]

latex:
  latex_documents:
    targetname: UW.tex

html:
#  home_page_in_navbar option: true
  extra_navbar: <button type="button" onclick="legibleFontSwitcher()">Switch Font</button>&nbsp;&nbsp;<button type="button" onclick="fontScaler(1.1)">&#10133;</button><button type="button" onclick="fontScaler(0.0)">&#9679;</button><button type="button" onclick="fontScaler(0.909)">&#10134;</button>  
  use_repository_button: true
  comments:
    hypothesis: true

sphinx:
  config:
    html_show_copyright: false
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    # html_extra_path: ['Figures/Movies']
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py

parse:
    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

  # nb_custom_formats:
  #         .py:
  #             - jupytext.reads
  #             - fmt: py

repository:
  url    : https://github.com/underworldcode/underworld3  # Online location of this book
  branch : main  # Which branch of the repository should be used when creating links (optional)
  path_to_book : "Jupyterbook"

# Temporarily, this is set to launch on an existing server with uw3 hand-built

launch_buttons:
   jupyterhub_url: "https://emsc4033.rses.underworldcloud.org"  # The URL for your JupyterHub. 
   binderhub_url:  ""  # The URL of the BinderHub (e.g., https://mybinder.org)
   notebook_interface: "classic" # "jupyterlab" or "classic"
   

execute:
  # exclude_patterns:
  #   - File.ipynb
  execute_notebooks: 'off'
  allow_errors : true # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.

bibtex_bibfiles:
   - UnderworldManual.bib
