name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build_docker_image:
    name: Build Underworld 3 Docker image
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
     
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWORD }}
      
      - name: Build Base Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          tags: underworldcode/carbonite
